 version: 2
 jobs:
   build:
      docker:
        - image: circleci/node:10.16.3
      working_directory: ~/ToDo/server

      steps:
        - checkout
        - run: npm install
        - run: cd server && npm install
        - run: npm test
        - run: echo "Success" 
