 version: 2
 jobs:
   build:
      docker:
        - image: circleci/node:10.16.3
      working_directory: ~/ToDo

      steps:
        - checkout
        - run: npm install
        - run: npm test
        - run: echo "Success" 
